"""changestothedb

Revision ID: bdf31f8ef2fb
Revises: dd6ba79dbd3a
Create Date: 2026-09-15 19:08:08.403675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdf31f8ef2fb'
down_revision: Union[str, Sequence[str], None] = 'dd6ba79dbd3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('barcode', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'products', ['barcode'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_column('products', 'barcode')
    # ### end Alembic commands ###
