"""table changes

Revision ID: dd6ba79dbd3a
Revises: 1c94501eb7d9
Create Date: 2026-08-27 20:15:17.789214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd6ba79dbd3a'
down_revision: Union[str, Sequence[str], None] = '1c94501eb7d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usercompany',
    sa.Column('id_usercompany', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_f', sa.String(), nullable=False),
    sa.Column('name_s', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.Column('ie', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_usercompany'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('email')
    )
    op.create_table('addresses',
    sa.Column('id_address', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('cep', sa.String(), nullable=False),
    sa.Column('logradouro', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('complement', sa.String(), nullable=True),
    sa.Column('neighborhood', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_address')
    )
    op.drop_constraint(op.f('users_rg_key'), 'users', type_='unique')
    op.drop_column('users', 'rg')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rg', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('users_rg_key'), 'users', ['rg'], postgresql_nulls_not_distinct=False)
    op.drop_table('addresses')
    op.drop_table('usercompany')
    # ### end Alembic commands ###
