"""rg added

Revision ID: ec4565504de2
Revises: d39d36d725bb
Create Date: 2026-08-04 14:18:24.558122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec4565504de2'
down_revision: Union[str, Sequence[str], None] = 'd39d36d725bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rg', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'users', ['rg'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'rg')
    # ### end Alembic commands ###
