"""major changes

Revision ID: fa1695971502
Revises: 271bc26ebc8c
Create Date: 2026-08-04 20:39:10.308716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa1695971502'
down_revision: Union[str, Sequence[str], None] = '271bc26ebc8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand', sa.String(), nullable=False))
    op.add_column('products', sa.Column('slug', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'products', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_column('products', 'slug')
    op.drop_column('products', 'brand')
    # ### end Alembic commands ###
